import Link from 'next/link';
import { services } from '@/data/services';
import { projects } from '@/data/projects';
import { site } from '@/data/site';
import { makeMetadata } from '@/lib/seo';
import { ServiceCard, ProjectCard, PricingCard } from '@/components/Cards';
import { FAQ } from '@/components/FAQ';
import { JsonLd } from '@/components/JsonLd';
export const metadata = makeMetadata('Digital Solutions Company in Shillong', site.description, '/');
const faq=[{q:'Do you work only with large companies?',a:'No. We support small, growing, and established businesses with flexible scope and pricing.'},{q:'Can we start small and scale later?',a:'Yes. We can start with a simple website or system and extend based on results.'}];
  const businessSchema={"@context":"https://schema.org","@type":"ProfessionalService",name:site.name,description:site.description,areaServed:"Shillong, Meghalaya",telephone:site.phone,email:site.email,address:{"@type":"PostalAddress",addressLocality:"Shillong",addressRegion:"Meghalaya",addressCountry:"IN"}};
  const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map((item)=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))};

export default function Home(){return <><JsonLd data={businessSchema} /><JsonLd data={faqSchema} /><section className='container-ui py-14'><p className='text-sm text-forest'>Based in Shillong, Meghalaya</p><h1 className='mt-3 text-4xl font-bold'>Shillong ITech<br/>Websites. Apps. Digital Systems.</h1><p className='mt-4 max-w-3xl'>{site.tagline}</p><div className='mt-6 flex flex-wrap gap-3'><a href={`tel:${site.phone}`} className='rounded-full bg-forest px-5 py-3 text-white'>Call Now</a><a href={`https://wa.me/${site.whatsapp.replace(/\D/g,'')}`} className='rounded-full bg-accent px-5 py-3 text-white'>Chat on WhatsApp</a><Link href='/contact' className='rounded-full border px-5 py-3'>Start a Project</Link><Link href='/services' className='rounded-full border px-5 py-3'>View Services</Link></div></section><section className='container-ui py-10'><h2 className='text-2xl font-semibold'>What We Do</h2><div className='mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3'>{services.map(s=><ServiceCard key={s.slug} service={s} />)}</div></section><section className='container-ui py-10'><h2 className='text-2xl font-semibold'>Featured Work</h2><div className='mt-5 grid gap-4 md:grid-cols-2'>{projects.map(p=><ProjectCard key={p.slug} project={p} />)}</div></section><section className='container-ui py-10'><h2 className='text-2xl font-semibold'>Flexible Pricing</h2><div className='mt-5 grid gap-4 md:grid-cols-3'><PricingCard title='Starter Website' price='Starting from ₹9,999' text='Up to 5 pages, responsive design, contact form, WhatsApp button and basic SEO.'/><PricingCard title='Business Website / Dashboard' price='Starting from ₹24,999' text='Admin panel, user management, reports, charts, and role-based scope.'/><PricingCard title='Custom Digital Solution' price='Custom Pricing' text='Websites, apps, dashboards, automation, APIs and integrations.'/></div><p className='mt-4 text-sm'>Final cost depends on your requirement. We suggest the simplest practical solution with no unnecessary cost.</p></section><section className='container-ui py-10'><h2 className='text-2xl font-semibold'>Quick Answers / FAQ</h2><div className='mt-4'><FAQ items={faq}/></div></section></>
}
